2020-07-11 10:30:22,793 INFO: Microblog startup [in C:\Users\jcumm\Documents\12-microblog\microblog\app\__init__.py:47]
2020-07-11 10:30:42,904 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NCwiZXhwIjoxNTk0NDc4NDMzLjIwODgyMjV9.EShUBlT_dIqA8cxSJQnFWRYy9n036LEMsa6syRiNYtw [GET] [in c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jcumm\Documents\12-microblog\microblog\app\routes.py", line 102, in reset_password
    user = User.verify_reset_password_token(token)
AttributeError: type object 'User' has no attribute 'verify_reset_password_token'
2020-07-11 10:32:11,126 INFO: Microblog startup [in C:\Users\jcumm\Documents\12-microblog\microblog\app\__init__.py:47]
2020-07-11 11:01:32,775 INFO: Microblog startup [in C:\Users\jcumm\Documents\12-microblog\microblog\app\__init__.py:47]
2020-07-11 11:01:59,663 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NCwiZXhwIjoxNTk0NDgwMzA5LjY2MjM3Njl9.VbULfUqZmYOCWlnwYyOV9cFubr7gFle1z5nX43nedSQ [GET] [in c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jcumm\Documents\12-microblog\microblog\app\routes.py", line 107, in reset_password
    user.set_password(form.password.data)
  File "C:\Users\jcumm\Documents\12-microblog\microblog\app\models.py", line 35, in set_password
    self.password_hash = generate_password_hash(password)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\werkzeug\security.py", line 203, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\werkzeug\security.py", line 153, in _hash_internal
    rv = pbkdf2_hex(password, salt, iterations, hashfunc=method)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\werkzeug\security.py", line 53, in pbkdf2_hex
    rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\werkzeug\security.py", line 87, in pbkdf2_bin
    return hashlib.pbkdf2_hmac(hash_name, data, salt, iterations, keylen)
TypeError: a bytes-like object is required, not 'NoneType'
2020-07-11 11:09:42,859 INFO: Microblog startup [in C:\Users\jcumm\Documents\12-microblog\microblog\app\__init__.py:47]
2020-07-11 11:10:23,688 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NCwiZXhwIjoxNTk0NDgwODAxLjU1NTUwMn0.Ij59Ucaowc8mt566KtsyhYa3nf__IHHAiYjtHZm0xJk [GET] [in c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jcumm\Documents\12-microblog\microblog\app\routes.py", line 107, in reset_password
    user.set_password(form.password.data)
  File "C:\Users\jcumm\Documents\12-microblog\microblog\app\models.py", line 35, in set_password
    self.password_hash = generate_password_hash(password)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\werkzeug\security.py", line 203, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\werkzeug\security.py", line 153, in _hash_internal
    rv = pbkdf2_hex(password, salt, iterations, hashfunc=method)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\werkzeug\security.py", line 53, in pbkdf2_hex
    rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\werkzeug\security.py", line 87, in pbkdf2_bin
    return hashlib.pbkdf2_hmac(hash_name, data, salt, iterations, keylen)
TypeError: a bytes-like object is required, not 'NoneType'
2020-07-11 11:12:47,916 INFO: Microblog startup [in C:\Users\jcumm\Documents\12-microblog\microblog\app\__init__.py:47]
